"""
Django settings for FurConnectApp project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Version string for display in footer
import subprocess
from datetime import datetime
try:
    from FurConnectApp import __version__
    # Try to get git commit hash and date
    git_hash = None
    git_date = None
    try:
        git_hash = subprocess.check_output([
            'git', 'rev-parse', 'HEAD'
        ], cwd=BASE_DIR, stderr=subprocess.DEVNULL).decode('utf-8').strip()[:6].upper()
        git_date_raw = subprocess.check_output([
            'git', 'show', '-s', '--format=%cd', '--date=format:%Y%m%d', 'HEAD'
        ], cwd=BASE_DIR, stderr=subprocess.DEVNULL).decode('utf-8').strip()
        git_date = git_date_raw
    except Exception:
        pass
    if git_hash and git_date:
        # Format: Version: ABCDEF (2026-03-09)
        # git_date is YYYYMMDD, convert to YYYY-MM-DD
        formatted_date = f"{git_date[:4]}-{git_date[4:6]}-{git_date[6:]}"
        FURCONNECT_VERSION = f"Version: {git_hash} ({formatted_date})"
    else:
        FURCONNECT_VERSION = f"Version: {__version__}"
except ImportError:
    FURCONNECT_VERSION = "dev"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-ozwj#9eg+=0leqx9pwzsgo@yqapfrzc3220(nfum7se6ie$tyq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ['1', 'true', 'yes']

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1,https://localhost').split(',')
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False').lower() in ['1', 'true', 'yes']
CSRF_COOKIE_HTTPONLY = os.environ.get('DJANGO_CSRF_COOKIE_HTTPONLY', 'True').lower() in ['1', 'true', 'yes']
CSRF_USE_SESSIONS = os.environ.get('DJANGO_CSRF_USE_SESSIONS', 'True').lower() in ['1', 'true', 'yes']
CSRF_COOKIE_SAMESITE = os.environ.get('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax')

# Session Settings
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False').lower() in ['1', 'true', 'yes']
SESSION_COOKIE_HTTPONLY = os.environ.get('DJANGO_SESSION_COOKIE_HTTPONLY', 'True').lower() in ['1', 'true', 'yes']
SESSION_COOKIE_SAMESITE = os.environ.get('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events.apps.EventsConfig',
    'widget_tweaks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FurConnectApp.urls'

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'FurConnectApp.settings.furconnect_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'FurConnectApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL configuration
LOGIN_URL = 'events:login'
LOGIN_REDIRECT_URL = 'schedule'
LOGOUT_REDIRECT_URL = 'events:login'

def furconnect_version(request):
    from django.conf import settings
    return {'FURCONNECT_VERSION': getattr(settings, 'FURCONNECT_VERSION', 'dev')}
